# Generated by Django 4.0.4 on 2022-05-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Night', 'Night Sky'), ('Thoery', 'Theoretical')], default='General', max_length=100),
        ),
    ]
